export const MOCK_ARTICLES = [
  {
    id: "1",
    title: "Empagliflozin and Cardiovascular Outcomes in Heart Failure with Preserved Ejection Fraction",
    authors: ["Anker SD", "Butler J", "Filippatos G", "Ferreira JP"],
    journal: "New England Journal of Medicine",
    published_date: "2024-11-15",
    doi: "10.1056/NEJMoa2107038",
    url: "https://www.nejm.org/doi/10.1056/NEJMoa2107038",
    abstract: "In patients with heart failure with preserved ejection fraction, the use of empagliflozin resulted in a significantly lower risk of cardiovascular death or worsening heart failure compared with placebo.",
    summary_pt: "Empagliflozina reduziu significativamente o risco de morte cardiovascular e piora da insuficiência cardíaca em pacientes com fração de ejeção preservada, abrindo nova fronteira terapêutica para essa população de difícil manejo.",
    specialty: "cardiologia",
    source: "rss",
    relevance_score: 9.5,
    impact_factor: 10,
    created_at: "2024-11-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Pembrolizumab versus chemotherapy for previously untreated, PD-L1-expressing, locally advanced or metastatic non-small-cell lung cancer (KEYNOTE-024): updated 5-year outcome",
    authors: ["Reck M", "Rodríguez-Abreu D", "Robinson AG"],
    journal: "The Lancet Oncology",
    published_date: "2024-10-22",
    doi: "10.1016/S1470-2045(24)00178-X",
    url: "https://www.thelancet.com/journals/lanonc/article/PIIS1470-2045(24)00178-X",
    abstract: "Five-year follow-up of KEYNOTE-024 confirms durable overall survival benefit with pembrolizumab as first-line therapy for PD-L1 TPS ≥50% non-small-cell lung cancer.",
    summary_pt: "Acompanhamento de 5 anos confirma benefício duradouro em sobrevida global com pembrolizumabe como primeira linha em NSCLC com PD-L1 ≥50%, consolidando imunoterapia como padrão ouro nessa população.",
    specialty: "oncologia",
    source: "rss",
    relevance_score: 9.2,
    impact_factor: 9,
    created_at: "2024-10-22T10:00:00Z",
  },
  {
    id: "3",
    title: "Lecanemab in Early Alzheimer's Disease: 18-Month Efficacy and Safety Results",
    authors: ["van Dyck CH", "Swanson CJ", "Aisen P", "Bateman RJ"],
    journal: "New England Journal of Medicine",
    published_date: "2024-09-10",
    doi: "10.1056/NEJMoa2212948",
    url: "https://www.nejm.org/doi/10.1056/NEJMoa2212948",
    abstract: "Lecanemab, a humanized IgG1 monoclonal antibody that targets amyloid beta, reduced markers of amyloid in early Alzheimer's disease and resulted in moderately less decline on measures of cognition and function at 18 months.",
    summary_pt: "Lecanemabe demonstrou redução significativa de marcadores de amiloide e menor declínio cognitivo em 18 meses na doença de Alzheimer precoce, representando primeiro modificador de doença clinicamente relevante aprovado.",
    specialty: "neurologia",
    source: "rss",
    relevance_score: 9.8,
    impact_factor: 10,
    created_at: "2024-09-10T10:00:00Z",
  },
  {
    id: "4",
    title: "Semaglutide and Cardiovascular Outcomes in Obesity without Diabetes",
    authors: ["Lincoff AM", "Brown-Frandsen K", "Colhoun HM"],
    journal: "New England Journal of Medicine",
    published_date: "2024-08-05",
    doi: "10.1056/NEJMoa2307563",
    url: "https://www.nejm.org/doi/10.1056/NEJMoa2307563",
    abstract: "Among patients with preexisting cardiovascular disease and obesity but without diabetes, treatment with semaglutide (2.4 mg weekly) was associated with a 20% reduction in cardiovascular events.",
    summary_pt: "Semaglutida 2,4mg semanal reduziu em 20% eventos cardiovasculares em pacientes obesos sem diabetes e com doença cardiovascular prévia, independente da perda de peso, ampliando indicação para prevenção secundária.",
    specialty: "endocrinologia",
    source: "rss",
    relevance_score: 9.7,
    impact_factor: 10,
    created_at: "2024-08-05T10:00:00Z",
  },
  {
    id: "5",
    title: "Nirsevimab for Prevention of RSV in Preterm and Term Infants",
    authors: ["Hammitt LL", "Dagan R", "Yuan Y", "Cots MV"],
    journal: "New England Journal of Medicine",
    published_date: "2024-07-20",
    doi: "10.1056/NEJMoa2110275",
    url: "https://www.nejm.org/doi/10.1056/NEJMoa2110275",
    abstract: "A single dose of nirsevimab, a long-acting monoclonal antibody, provided significant protection against medically attended RSV-associated lower respiratory tract infection in infants.",
    summary_pt: "Dose única de nirsevimabe (anticorpo monoclonal de longa duração) reduziu 74,5% as hospitalizações por RSV em lactentes, revolucionando a prevenção de bronquiolite — principal causa de internação em menores de 1 ano.",
    specialty: "pediatria",
    source: "pubmed",
    relevance_score: 9.3,
    impact_factor: 10,
    created_at: "2024-07-20T10:00:00Z",
  },
  {
    id: "6",
    title: "Esketamine Nasal Spray for Treatment-Resistant Depression: 52-Week Safety Study",
    authors: ["Daly EJ", "Trivedi MH", "Janik A"],
    journal: "JAMA Psychiatry",
    published_date: "2024-06-15",
    doi: "10.1001/jamapsychiatry.2024.0440",
    url: "https://jamanetwork.com/journals/jamapsychiatry/fullarticle/2024.0440",
    abstract: "Long-term safety and tolerability of esketamine nasal spray in treatment-resistant depression was confirmed over 52 weeks with no new safety signals identified.",
    summary_pt: "Estudo de 52 semanas confirma segurança e tolerabilidade do esketamina intranasal na depressão resistente ao tratamento, sem novos sinais de segurança, sustentando seu uso a longo prazo nessa população grave.",
    specialty: "psiquiatria",
    source: "pubmed",
    relevance_score: 8.8,
    impact_factor: 9,
    created_at: "2024-06-15T10:00:00Z",
  },
  {
    id: "7",
    title: "Trastuzumab Deruxtecan versus Pertuzumab plus Trastuzumab for HER2-Positive Metastatic Breast Cancer",
    authors: ["Cortés J", "Kim SB", "Chung WP"],
    journal: "New England Journal of Medicine",
    published_date: "2024-05-30",
    doi: "10.1056/NEJMoa2403046",
    url: "https://www.nejm.org/doi/10.1056/NEJMoa2403046",
    abstract: "Trastuzumab deruxtecan (T-DXd) demonstrated superior progression-free and overall survival versus pertuzumab plus trastuzumab as first-line therapy in HER2-positive metastatic breast cancer.",
    summary_pt: "T-DXd demonstrou superioridade sobre pertuzumabe+trastuzumabe como primeira linha no câncer de mama HER2+ metastático, com melhora significativa em SLP e SG, estabelecendo novo padrão de tratamento.",
    specialty: "oncologia",
    source: "rss",
    relevance_score: 9.6,
    impact_factor: 10,
    created_at: "2024-05-30T10:00:00Z",
  },
  {
    id: "8",
    title: "Gut microbiota composition and diversity in children with and without type 1 diabetes in Brazil",
    authors: ["Ferreira APS", "Costa RS", "Cunha MLR"],
    journal: "Brazilian Journal of Medical and Biological Research",
    published_date: "2024-04-12",
    doi: "10.1590/1414-431X2024e13201",
    url: "https://www.scielo.br/j/bjmbr/a/e13201",
    abstract: "Este estudo avaliou a composição e diversidade do microbioma intestinal em crianças brasileiras com e sem diabetes tipo 1, encontrando reduções significativas de Lactobacillus e Bifidobacterium no grupo com DM1.",
    summary_pt: "Pesquisa brasileira demonstra redução do microbioma protetor (Lactobacillus, Bifidobacterium) em crianças com DM1, sugerindo papel da disbiose na patogênese e abrindo possibilidades terapêuticas com probióticos.",
    specialty: "pediatria",
    source: "scielo",
    relevance_score: 7.8,
    impact_factor: 3,
    created_at: "2024-04-12T10:00:00Z",
  },
  {
    id: "9",
    title: "Dapagliflozin in Patients with Chronic Kidney Disease: DAPA-CKD Final Analysis",
    authors: ["Heerspink HJL", "Stefánsson BV", "Correa-Rotter R"],
    journal: "New England Journal of Medicine",
    published_date: "2024-03-25",
    doi: "10.1056/NEJMoa2024816",
    url: "https://www.nejm.org/doi/10.1056/NEJMoa2024816",
    abstract: "Dapagliflozin reduced the risk of sustained decline in eGFR, end-stage kidney disease, and death from renal or cardiovascular causes in patients with chronic kidney disease with or without diabetes.",
    summary_pt: "Dapagliflozina reduz progressão da DRC independente da presença de diabetes, com benefícios em desfechos renais e cardiovasculares, consolidando os iSGLT2 como nefroprotores de amplo espectro.",
    specialty: "nefrologia",
    source: "pubmed",
    relevance_score: 9.4,
    impact_factor: 10,
    created_at: "2024-03-25T10:00:00Z",
  },
  {
    id: "10",
    title: "Dupilumab for Moderate-to-Severe Atopic Dermatitis: Long-Term Safety and Efficacy",
    authors: ["Blauvelt A", "de Bruin-Weller M", "Gooderham M"],
    journal: "JAMA Dermatology",
    published_date: "2024-02-14",
    doi: "10.1001/jamadermatol.2024.0021",
    url: "https://jamanetwork.com/journals/jamadermatology/fullarticle/2024.0021",
    abstract: "Extended use of dupilumab demonstrated sustained efficacy and acceptable safety profile over 3 years in moderate-to-severe atopic dermatitis, with no new safety signals.",
    summary_pt: "Dupilumabe mantém eficácia e segurança em 3 anos de uso na dermatite atópica moderada-grave, sem novos sinais de segurança, confirmando sua posição como tratamento de longa duração.",
    specialty: "dermatologia",
    source: "pubmed",
    relevance_score: 8.6,
    impact_factor: 8,
    created_at: "2024-02-14T10:00:00Z",
  },
  {
    id: "11",
    title: "Budesonide-Formoterol Rescue Therapy versus Albuterol in Adults with Mild-to-Moderate Asthma",
    authors: ["O'Byrne PM", "FitzGerald JM", "Bateman ED"],
    journal: "New England Journal of Medicine",
    published_date: "2024-01-18",
    doi: "10.1056/NEJMoa2307071",
    url: "https://www.nejm.org/doi/10.1056/NEJMoa2307071",
    abstract: "As-needed budesonide-formoterol for mild-to-moderate asthma was superior to as-needed albuterol in reducing severe exacerbations without regular maintenance therapy.",
    summary_pt: "Budesonida-formoterol de resgate superior ao salbutamol em asma leve-moderada, reduzindo exacerbações graves sem terapia de manutenção regular — mudança de paradigma no manejo da asma.",
    specialty: "pneumologia",
    source: "rss",
    relevance_score: 8.9,
    impact_factor: 10,
    created_at: "2024-01-18T10:00:00Z",
  },
  {
    id: "12",
    title: "Hipertensão arterial sistêmica e fatores de risco cardiovascular em adultos brasileiros: Estudo ELSA-Brasil",
    authors: ["Benseñor IM", "Lotufo PA", "Schmidt MI", "Griep RH"],
    journal: "Cadernos de Saúde Pública",
    published_date: "2024-01-08",
    doi: "10.1590/0102-311X00012323",
    url: "https://www.scielo.br/j/csp/a/00012323",
    abstract: "Análise longitudinal do ELSA-Brasil avalia prevalência de hipertensão e fatores associados em coorte de funcionários públicos brasileiros, com foco em desigualdades regionais e sociais.",
    summary_pt: "Dados do ELSA-Brasil revelam prevalência de 35,8% de hipertensão em adultos brasileiros, com gradiente socioeconômico marcado, enfatizando necessidade de políticas públicas diferenciadas por região.",
    specialty: "clinica-medica",
    source: "scielo",
    relevance_score: 8.2,
    impact_factor: 4,
    created_at: "2024-01-08T10:00:00Z",
  },
];

export const MOCK_SPECIALTIES = [
  { slug: "cardiologia", label: "Cardiologia", icon: "heart", color: "red", article_count: 47 },
  { slug: "oncologia", label: "Oncologia", icon: "microscope", color: "purple", article_count: 63 },
  { slug: "neurologia", label: "Neurologia", icon: "brain", color: "indigo", article_count: 38 },
  { slug: "endocrinologia", label: "Endocrinologia", icon: "activity", color: "yellow", article_count: 55 },
  { slug: "pediatria", label: "Pediatria", icon: "users", color: "green", article_count: 41 },
  { slug: "psiquiatria", label: "Psiquiatria", icon: "brain", color: "teal", article_count: 29 },
  { slug: "ginecologia", label: "Ginecologia e Obstetrícia", icon: "heart", color: "pink", article_count: 33 },
  { slug: "infectologia", label: "Infectologia", icon: "shield", color: "orange", article_count: 52 },
  { slug: "cirurgia", label: "Cirurgia", icon: "scissors", color: "gray", article_count: 26 },
  { slug: "clinica-medica", label: "Clínica Médica", icon: "stethoscope", color: "blue", article_count: 71 },
  { slug: "reumatologia", label: "Reumatologia", icon: "activity", color: "amber", article_count: 24 },
  { slug: "nefrologia", label: "Nefrologia", icon: "droplet", color: "cyan", article_count: 31 },
  { slug: "pneumologia", label: "Pneumologia", icon: "wind", color: "sky", article_count: 37 },
  { slug: "gastroenterologia", label: "Gastroenterologia", icon: "activity", color: "lime", article_count: 44 },
  { slug: "dermatologia", label: "Dermatologia", icon: "layers", color: "rose", article_count: 28 },
];
